package model;

public enum ModelPropertiesEnum {
    SCHEDULED_TASKNAME_CHANGED,
    SCHEDULED_TASKPARAMETER_CHANGED,
    SELECTED_TASK_CHANGED,
    CHOSEN_TIMING_DURATION_DELAY_CHANGED,
    TIMER_TICK
}
