package model;

public enum ModelObservableEvents {
    SCHEDULED_TASK_CREATED,
    SCHEDULED_TASK_STATUS_CHANGED,
    SCHEDULED_TASK_FINISHED,
    SCHEDULED_TASK_FINISHED_WITH_ERRORS,
    SELECTED_TASK_CHANGED,
    LAST_SCHEDULED_TASK_CHANGED,
    CHOSEN_TIMING_DURATION_DELAY_CHANGED,
    TIMER_TICK,

}
