package view;

import tasks.TaskTemplate;
import org.jetbrains.annotations.NotNull;
import view.choosetasks.TaskUI;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;


public class MainWindowCreator {
    private JPanel panelGui;
    private JPanel panelChooseTasks;
    private JPanel panelChooseTiming;
    private JPanel panelCountdown;
    private JPanel panelControls;
    private JPanel panelStatusbar;
    JLabel labelStatusbar;
    JButton buttonSubmit;
    JButton buttonExit;
    JButton buttonShowScheduledTasks;
    JSpinner spinnerChooseTiming;
    JLabel labelLastWhenElapsed;
    JLabel labelLastDurationDelay;
    JButton buttonCancel;
    JLabel labelWhenElapsed;
    JLabel labelDurationDelay;
    JLabel labelLastId;

    final static int TIMING_STEP_IN_MINUTES = 15;
    final static String TIMING_DEFAULT_VALUE = "01:00";

    private final JFrame guiFrame;
    final TaskUI uiChooseTask = new TaskUI();;

    MainWindowCreator(@NotNull List<TaskTemplate> tasks) {
        guiFrame = new JFrame("Vypnutí PC");
        guiFrame.setContentPane(panelGui);
        guiFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // MUST CHANGE AUTOGENERATED JPANEL LAYOUT TO NON IDEA-MANAGED
        JPanel generatedChooseTasksPanel = uiChooseTask.createUIChooseTask(tasks);
        panelChooseTasks.add(generatedChooseTasksPanel);
    }

    void run() {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                guiFrame.pack();
                setCenteredToGoldenRatio(guiFrame);
                guiFrame.setVisible(true);
            }
        });
    }

    void showErrorPopup(@NotNull String errorMessage) {
        JOptionPane.showMessageDialog(guiFrame, errorMessage, "Neočekávaná chyba.", JOptionPane.ERROR_MESSAGE);
    }

    String getTimingValue() {
        return spinnerChooseTiming.getValue().toString();
    }

    void setSelectedTaskName(@NotNull String taskName) {
        uiChooseTask.setSelectedTaskName(taskName);
    }

    String getSelectedTaskName() {
        return uiChooseTask.getSelectedTaskName();
    }

    String getSelectedTaskParameter() {
        return uiChooseTask.getSelectedTaskParameter();
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        SpinnerListModel slm = new SpinnerListModel(generateTimeSequence(TIMING_STEP_IN_MINUTES));
        spinnerChooseTiming = new javax.swing.JSpinner(slm);
        spinnerChooseTiming.setValue(TIMING_DEFAULT_VALUE);
    }

    /**
     * Generates List sequence of Strings
     * @param step in minutes determines step
     */
    private List<String> generateTimeSequence(int step) {
        java.util.List<String> sequence = new ArrayList<>();
        int onehour=60;

        for(int i=0; i<60*12; i+=step) {
            String hourPart = String.format("%02d", i/onehour);
            String minutePart = String.format("%02d", i%onehour);
            sequence.add(hourPart + ':' + minutePart);
        }
        return sequence;
    }

    /**
     * Callable after swing frame.pack() function to center application window.
     */
    private static void setCenteredToGoldenRatio(JFrame frame) {
        Dimension screenDimension = Toolkit.getDefaultToolkit().getScreenSize();
        int screenHeight = (int) screenDimension.getHeight();
        int screenWidth = (int) screenDimension.getWidth();

        int frameHeight = frame.getHeight();
        int frameWidth = frame.getWidth();

        int goldenRatioHeight = (int) ((screenHeight - frameHeight) * 0.38);

        frame.setLocation((screenWidth / 2) - (frameWidth / 2), goldenRatioHeight);
    }
}
