package view.main;

import controller.ControllerMainImpl;
import model.ModelObservableEvents;
import model.StateModel;
import model.TaskModel;
import model.TimeManager;
import org.jetbrains.annotations.NotNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import tasks.TaskTemplate;
import view.AbstractWindow;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.util.ArrayList;
import java.util.List;


public class MainWindow extends AbstractWindow {
    private JPanel panelGui;
    private JPanel panelChooseTasks;
    private JPanel panelChooseTiming;
    private JPanel panelCountdown;
    private JPanel panelControls;
    private JPanel panelStatusbar;
    private JLabel labelStatusbar;
    private JButton buttonSubmit;
    private JButton buttonExit;
    private JButton buttonShowScheduledTasks;
    private JSpinner spinnerChooseTiming;
    private JLabel labelLastWhenElapsed;
    private JLabel labelLastDurationDelay;
    private JButton buttonCancel;
    private JLabel labelWhenElapsed;
    private JLabel labelDurationDelay;
    private JLabel labelLastId;

    static final int TIMING_STEP_IN_MINUTES = 15;
    static final String TIMING_DEFAULT_VALUE = "01:00";

    private static final Logger logger = LoggerFactory.getLogger(MainWindow.class);

    private final ChooseTaskUI uiChooseTask = new ChooseTaskUI();

    public MainWindow(@NotNull ControllerMainImpl controller, @NotNull TaskModel taskModel) {
        super(controller, new JFrame("Vypnutí PC"));

        guiFrame.setContentPane(panelGui);
        guiFrame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        List<TaskTemplate> tasks = taskModel.getTaskTemplates();

        // MUST CHANGE AUTOGENERATED JPANEL LAYOUT TO NON IDEA-MANAGED OTHERWISE ERROR
        JPanel generatedChooseTasksPanel = uiChooseTask.createUIChooseTask(tasks);
        panelChooseTasks.add(generatedChooseTasksPanel);

        spinnerChooseTiming.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent changeEvent) {
                String newTiming = getTimingValue();
                controller.changedTimingByUser(newTiming);
            }
        });
        buttonSubmit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                String selectedTaskName = getSelectedTaskName();
                String timing = getTimingValue();
                String selectedTaskParameter = getSelectedTaskParameter();
                controller.actionNewTaskScheduledByUser(selectedTaskName, timing, selectedTaskParameter);
            }
        });
        buttonShowScheduledTasks.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                controller.actionShowScheduledTasks();
            }
        });
        buttonExit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                controller.actionExitByUser();
            }
        });
        uiChooseTask.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                String selectedTaskName = getSelectedTaskName();
                controller.actionNewTaskSelectedByUser(selectedTaskName);
            }
        });
        buttonCancel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                controller.actionCancelLastScheduledTask();
            }
        });
    }

    private String getTimingValue() {
        return spinnerChooseTiming.getValue().toString();
    }

    private void setSelectedTaskName(@NotNull String taskName) {
        uiChooseTask.setSelectedTaskName(taskName);
    }

    private String getSelectedTaskName() {
        return uiChooseTask.getSelectedTaskName();
    }

    private String getSelectedTaskParameter() {
        return uiChooseTask.getSelectedTaskParameter();
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        SpinnerListModel slm = new SpinnerListModel(generateTimeSequence(TIMING_STEP_IN_MINUTES));
        spinnerChooseTiming = new javax.swing.JSpinner(slm);
        spinnerChooseTiming.setValue(TIMING_DEFAULT_VALUE);
    }

    /**
     * Generates List sequence of Strings
     *
     * @param step in minutes determines step
     */
    private List<String> generateTimeSequence(int step) {
        List<String> sequence = new ArrayList<>();
        int onehour = 60;

        for (int i = 0; i < 60 * 12; i += step) {
            String hourPart = String.format("%02d", i / onehour);
            String minutePart = String.format("%02d", i % onehour);
            sequence.add(hourPart + ':' + minutePart);
        }
        return sequence;
    }

    private void refreshTimingCountdowns(@NotNull TimeManager durationDelay) {
        labelDurationDelay.setText(durationDelay.getRemainingDurationInHHMMSS_ifElapsedZeros());
        labelWhenElapsed.setText(durationDelay.getWhenElapsedInHHMM());
    }

    public void refreshLastScheduledTaskTimingCountdowns(@NotNull TimeManager durationDelay) {
        labelLastDurationDelay.setText(durationDelay.getRemainingDurationInHHMMSS_ifElapsedZeros());
        labelLastWhenElapsed.setText(durationDelay.getWhenElapsedInHHMM());
    }

    public void refreshViewFromModel(@NotNull StateModel stateModel) {
        setSelectedTaskName(stateModel.getSelectedTaskName());
        spinnerChooseTiming.getModel().setValue(stateModel.getTimingDurationDelay());
        refreshTimingCountdowns(new TimeManager(stateModel.getTimingDurationDelay()));
        updateLastScheduledTask(stateModel.getLastScheduledTaskId());
    }

    private void updateLastScheduledTask(int id) {
        labelLastId.setText(String.valueOf(id));
    }

    public void showInfoMessageToUser(@NotNull String message) {
        labelStatusbar.setText(message);
    }

    public void showErrorMessageToUser(@NotNull String errorMessage) {
        showInfoMessageToUser(errorMessage);
        showErrorPopup(errorMessage);
    }

    @Override
    public void modelPropertyChange(PropertyChangeEvent evt) {
        String propertyName = evt.getPropertyName();

        //TODO exception illegal argument
        switch (ModelObservableEvents.valueOf(propertyName)) {
            case SELECTED_TIMING_DURATION_DELAY_CHANGED: {
                logger.debug("Chose timing has changed. {} -> {}", evt.getOldValue(), evt.getNewValue());
                String newTimingDurationDelay = evt.getNewValue().toString();
                TimeManager timeManager = new TimeManager(newTimingDurationDelay);
                refreshTimingCountdowns(timeManager);
                break;
            }
            case TIMER_TICK: {
                //controller.eventTimerTickReceived();
                break;
            }
            case LAST_SCHEDULED_TASK_CHANGED: {
                int id = (int) evt.getNewValue();
                updateLastScheduledTask(id);
                break;
            }
        }
    }
}
